### PR TITLE
refactor GTFS import

### PR DESCRIPTION
**Pull request by derhuerst**
- introduce a mapping file `read-gtfs/mapping`
- open the DB in `index.js`, pass it into `read-gtfs/import`

Currently, we have a structure like this:

```
-- index.js --------------------------------------------------
| -- read-gtfs/index --------------------  - generate-fptf - |
| | - read-gtfs/import -  - DB reader - |  | ...           | |
| | | opens LevelDB    |  |           | |  ----------------- |
| ----------------------  ---------------                    |
--------------------------------------------------------------
```

This PR changes it to something like this:

```
-- index.js ----------------------------------------------------------
| opens LevelDB                                                      |
| - read-gtfs/read -  - read-gtfs/import -  - read-gtfs/db-reader -  |
| | ...            |  | ...              |  | ...                 |  |
| ------------------  --------------------  -----------------------  |
| - generate-fptf -                                                  |
| | ...           |                                                  |
| -----------------                                                  |
----------------------------------------------------------------------
```

I tries to let `index.js` glue together all utilities, instead of having them nested.

### CODE REVIEW

**Comment by derhuerst** [comment]
⚠️ WIP, don't merge yet.

**Comment by derhuerst** [comment]
Haven't tried yet if it works.

**Comment by juliuste** [comment]
Is this still WIP? Did you test it yet?

**Comment by derhuerst** [comment]
Not yet.

**Comment by derhuerst** [comment]
What GTFS dump should I test with?

**Comment by derhuerst** [comment]
bump.

**Comment by juliuste** [comment]
Maybe DB, VBB and [Norway](https://storage.googleapis.com/marduk-production/outbound/gtfs/rb_norway-aggregated-gtfs.zip)

**Comment by derhuerst** [comment]
afaict this seems to work.

I will submit follow-up PRs for more compact data storage and improved code readabiliy. At the latest, I will then further test this PR.

**Comment by derhuerst** [comment]
potentially controversial changes in this PR:

- I increased the minimum Node version for this lib to `7.6` in order to use `async`/`await`.
- I removed `shrinkwrap.yaml` in favour of `package-lock.json`.

**Pull request merged**
